module.exports = [
  { ignores: ["dist/**", "node_modules/**", "artifacts/**"] },
  {
    files: ["src/**/*.{js,jsx,mjs}", "vendor/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        __DESIGN_DEMO_VERSION__: "readonly",
        window: "readonly",
        indexedDB: "readonly",
        document: "readonly",
        location: "readonly",
        fetch: "readonly",
        AbortSignal: "readonly",
        AbortController: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        ResizeObserver: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
      },
    },
    plugins: { "react-hooks": require("eslint-plugin-react-hooks") },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "no-unused-vars": [
        "error",
        { varsIgnorePattern: "^[A-Z]", argsIgnorePattern: "^_" },
      ],
      "no-undef": "error",
      "no-unreachable": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-eval": "error",
    },
  },
  {
    files: ["legacy/dashboard-*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        document: "readonly",
        L: "readonly",
        module: "readonly",
        location: "readonly",
        fetch: "readonly",
        AbortSignal: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      eqeqeq: ["error", "always"],
      "no-eval": "error",
    },
  },
];
