const {chromium, expect} = require('@playwright/test');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 try {
  const page=await browser.newPage({viewport:{width:1512,height:1100},timezoneId:'America/Los_Angeles',locale:'en-US'});
  const errors=[],writes=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.method());});
  const state={schema_version:'coordination-state-1',scenario_id:'history-test',epoch:'2026-09-20T00:00:00Z',snapshot_id:'h1',revision:1,as_of:'2026-09-20T00:30:00Z',assets:[{asset_id:'a',name:'First location',latitude:41,longitude:2}],contacts:{ranked:[],review:[]},calls:[],teams:[{team_id:'crew',name:'History crew'}],plan:{locations:[],response:{teams:[{team_id:'crew',tasks:[{asset_id:'a',action_id:'one',status:'proposed'}]}]}},events:[{event_id:'one',kind:'assessment',as_of:'2026-09-20T00:30:00Z',notes:'Earlier evidence'}],tasks:[],errors:[]};
  await page.route('**/api/state',r=>r.fulfill({json:state}));
  await page.route('**/api/crew-approvals?*',r=>{
   const params=Object.fromEntries(new URL(r.request().url()).searchParams);
   return r.fulfill({json:{...params,revision:Number(params.revision),analyst:'@mirrdj',plans:[{team_id:'crew',can_confirm:true,plan_version:'v'+params.revision,approval:null}],events:[]}});
  });
  let stream;
  await page.routeWebSocket('**/api/updates*',ws=>{stream=ws;});
  const base=process.env.DASHBOARD_BASE_URL||'http://127.0.0.1:18522';
  await page.goto(base+'/#/overview');
  await expect(page.getByLabel('Snapshot time')).toHaveAttribute('max','0');
  await expect.poll(()=>!!stream).toBe(true);
  await expect(page.getByLabel('Time travel')).toContainText('Sep 19');
  state.revision=2;state.snapshot_id='h2';state.as_of='2026-09-20T01:00:00Z';
  state.assets.push({asset_id:'b',name:'Second location'});
  state.events=[{event_id:'two',kind:'assessment',as_of:state.as_of,notes:'Current evidence'}];
  stream.send(JSON.stringify(state));
  await expect(page.getByLabel('Snapshot time')).toHaveAttribute('max','1');
  await page.reload();
  await expect(page.getByLabel('Snapshot time')).toHaveAttribute('max','1');
  await expect(page.getByTestId('metric-structures')).toContainText('2');
  await page.getByRole('button',{name:'Previous',exact:true}).click();
  await expect(page.getByTestId('metric-structures')).toContainText('1');
  await page.getByRole('button',{name:'Review plan for History crew',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('Historical view. Return to current state');
  await expect(page.getByRole('dialog').getByRole('button',{name:'Confirm crew plan',exact:true})).toBeDisabled();
  state.revision=3;state.snapshot_id='h3';state.as_of='2026-09-20T01:15:00Z';
  state.assets.push({asset_id:'c',name:'Third location'});
  state.events=[{event_id:'three',kind:'assessment',as_of:state.as_of,notes:'Newest evidence'}];
  stream.send(JSON.stringify(state));
  await expect(page.getByLabel('Snapshot time')).toHaveAttribute('max','2');
  await expect(page.getByRole('dialog').getByRole('button',{name:'Confirm crew plan',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Close details'}).click();
  await expect(page.getByTestId('metric-structures')).toContainText('1');
  await page.getByRole('link',{name:'Activity log',exact:true}).click();
  await expect(page.locator('tbody')).toContainText('Earlier evidence');
  await expect(page.locator('tbody')).not.toContainText('Newest evidence');
  await page.getByRole('button',{name:'Return to current',exact:true}).click();
  await expect(page.locator('tbody')).toContainText('Newest evidence');
  await page.getByRole('link',{name:'Overview',exact:true}).click();
  await page.getByRole('button',{name:'Review plan for History crew',exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('button',{name:'Confirm crew plan',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Close details'}).click();
  await page.getByLabel('Data source').selectOption('demo');
  await expect(page.getByLabel('Snapshot time')).toHaveAttribute('max','3');
  await expect(page.getByLabel('Time travel')).toContainText('Generated demo history');
  await page.getByRole('button',{name:'Previous',exact:true}).click();
  await page.getByRole('button',{name:'Previous',exact:true}).click();
  await expect(page.getByTestId('metric-active')).toContainText('2');
  await page.screenshot({path:'artifacts/persisted-history.png',animations:'disabled'});
  await page.reload();
  await expect(page.getByLabel('Snapshot time')).toHaveAttribute('max','3');
  assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
  console.log('Timeline browser passed: persisted reload, generated history, pinned earlier state, new updates, approval guard, log isolation, local timezone and source isolation; no writes.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
